use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SystemInfo {
    pub user: String,
    pub hostname: String,
    pub os: Option<String>,
    pub host: Option<String>,
    pub kernel: Option<String>,
    pub uptime: Option<String>,
    pub packages: Option<String>,
    pub shell: Option<String>,
    pub display: Option<String>,
    pub de: Option<String>,
    pub wm: Option<String>,
    pub wm_theme: Option<String>,
    pub theme: Option<String>,
    pub icons: Option<String>,
    pub font: Option<String>,
    pub cursor: Option<String>,
    pub terminal: Option<String>,
    pub terminal_font: Option<String>,
    pub cpu: Option<String>,
    pub gpu: Option<String>,
    pub memory: Option<String>,
    pub swap: Option<String>,
    pub disk: Option<Vec<String>>,
    pub battery: Option<String>,
    pub power_adapter: Option<String>,
    pub audio: Option<String>,
    pub local_ip: Option<String>,
    pub public_ip: Option<String>,
    pub locale: Option<String>,
    pub distro_id: String,
    pub distro_name: String,
}
