[package]
name = "rustfetch"
version = "0.1.0"
edition = "2021"
authors = ["Zack <https://github.com/zackmsa777-a11y>"]
description = "A blazingly fast, highly extensible, and feature-rich system information tool written in Rust with fastfetch parity and multi-distro logos"
repository = "https://github.com/zackmsa777-a11y/rustfetch"
homepage = "https://github.com/zackmsa777-a11y/rustfetch"
documentation = "https://docs.rs/rustfetch"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["fetch", "system-info", "fastfetch", "neofetch", "cli"]
categories = ["command-line-utilities", "os"]

[dependencies]
libc = "0.2.189"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
