blank_issues_enabled: true
contact_links:
  - name: Ask Questions & Discussions
    url: https://github.com/zackmsa777-a11y/rustfetch/discussions
    about: Please ask questions and discuss ideas on GitHub Discussions.
