name: Feature Request
description: Suggest an idea or new module for rustfetch
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make `rustfetch` even faster or support new hardware / logos? Let us know!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem or limitation is.
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution / Feature
      description: Describe the new module, logo, or CLI functionality you would like to see added.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you considered.
